# Generated by Django 5.1.7 on 2025-03-28 21:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('last_update', models.DateField(auto_now=True)),
                ('create_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
